### ISSUE TITLE
RH AAP section updates

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#190]
**RH AAP section updates:**

- This section should have a grey background black-200 #F0F0F0
- There should be 40 px to the section header & RH AAP logo
- The header should be RH Text with a font size of 18 px / Bold
- There should be 24 px of padding between the section header and the following paragraphs
- The paragraphs should be RH Text with a font size of 18 px / Regular
- There should be 32 px of padding from the last paragraph to the button
- There should be 40 px of padding from the button to the end of the section
- There should be 64 px of padding between the RH AAP logo and content

Mockup:
<img width="502" alt="Screenshot 2023-09-26 at 10 49 57 AM" src="https://github.com/ansible-community/community-website/assets/98424339/66935d93-9ce8-4f73-bcc6-4de4a0c30ac1">

Updated Marvel: https://marvelapp.com/prototype/8bgeig6

**Comment by oraNod** [comment]
@tiyiprh Where did that "Extend the power of automation" phrase come from?

Let's also try and keep all text / wording changes separate to any style changes.

**Comment by tiyiprh** [comment]
I found it here: https://www.ansible.com/overview/it-automation
It is toward the middle of the page. We don't have to keep this exact wording, I just felt like it was a good segue and description of the distinction between the two.

<img width="1309" alt="Screenshot 2023-09-27 at 9 31 52 AM" src="https://github.com/ansible-community/community-website/assets/98424339/2aef7d94-e199-4e42-bd38-491ced684d1d">

**Comment by oraNod** [comment]
Thanks @tiyiprh I think that sort of content can put us at risk of drift if the marketing team refreshes that wording down the line. I'd also be cautious of poaching too much marketing content because the language doesn't always align with community content.

While revamping `docs.ansible.com` I learned that several community users have always felt that the proximity to Red Hat marketing content isn't always comfortable or it was a little "too pushy". There is certainly a path from community users to the platform. But I just feel like we need to be mindful of the balance.

All that aside I think that extra line in bold looks kind of stranded and is somewhat distracting. But if you do think it should go in, maybe we can create a PR now to preview it and get some other thoughts? What do you think?

**Comment by tiyiprh** [comment]
That makes sense. Where is the current content from? I think the current one is also fine so if you feel just to keep it as it, that's good with me

**Comment by oraNod** [comment]
I think some of the current content was also "borrowed" from marketing but I don't recall the exact source. We did some work on that back in April/May with the initial prototype. But now that you ask I'm not super sure about it. I'm pretty sure we're going to get some folks from the marketing team looking at this site in the next week or two anyway so maybe it does make sense to hold off on further changes.

**Comment by oraNod** [comment]
Thanks for creating this @tiyiprh I think we should be good to close this issue. Please either close or let me know if there's anything outstanding.

**Comment by tiyiprh** [comment]
I think we can close this one but I will create another one for looking at the spacing between the RHAAP icon and the text.
