### ISSUE TITLE
Agree on wishlist for the MVP for new community site

### ISSUE THREAD

**Issue by samccann** [ansible-community/community-website#20]
We need to come to an early consensus on what we require from this new site. This should be in a format easy for community members to comment on or add items to (potentially hackmd?)

MVP = Minimum viable product 

NOTE: This is not designing wireframes but more a set of important components or characteristics that must be in the new site. Some items may not be part of the first deployment of the new site. This is an iterative process.

**Comment by Andersson007** [comment]
Have we announced the doc yet? I see only two comments by Sandra

**Comment by samccann** [comment]
I think we decided at this point that the website decisions are being made by the website WG channel itself. We will go for feedback of course once we have prototype pages available etc.

**Comment by samccann** [comment]
Tho could use help getting that channel more active in feeback on the wishlist :-)

**Comment by cybette** [comment]
Mentioned in [Bullhorn 97](https://mailchi.mp/redhat/the-bullhorn-97)

**Comment by oraNod** [comment]
@samccann Connecting this to a discussion I had with @cybette plus the convo around the "alpha candidate" label. There are a few things going on so apologies for the incoming wall 'o text.

- MVP has less favourable optics because "p = product"
- "v = viable" Right now we have a landing page. That's not really viable for the community and does not fulfill any real need. It basically just gives another way to subscribe to the Bullhorn.

To get to something that is viable for the community we have two streams of work:

- UX / UI to get each part of the site (index, blog, pages) tied together
- Identify content that goes into the pages of the site (also referred to as sub-pages)

For that second stream - content that goes into the pages - I think we need to continue using this issue to identify our personas and map out their journeys. When we get to that stage we'll have a more complete picture of the minimum set of content that will be viable to the community.

That is the point I would call beta. When both those streams of work are complete and we can start plugging content into the site.

**Comment by oraNod** [comment]
Hmm. Maybe that comment is better in the website WG channel. But I think we should update / tweak this issue to track the effort to identify website personas and journeys because that work isn't done and it's what we should actually use to build the site.

**Comment by samccann** [comment]
moving this higher discussion to https://github.com/ansible-community/community-website/issues/44#issuecomment-1514733238

**Comment by samccann** [comment]
Closing as done - we have a proof of concept done.

**Comment by oraNod** [comment]
POC commit is https://github.com/ansible-community/community-website/commit/620a56aaeead497233138cca96075ca6153fd1be
