### ISSUE TITLE
"Get started with Ansible" button needs padding and hover state should be black vs cyan

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#252]
The "Get started with Ansible" button needs more padding (like previous versions before) and the hover state should be black vs cyan. This hover pattern would apply to other primary buttons as well (such as the subscribe section)
<img width="348" alt="Screenshot 2023-10-04 at 4 50 50 PM" src="https://github.com/ansible-community/community-website/assets/98424339/5f3f6a81-989d-4349-973c-0c90ab077adb">

**Comment by oraNod** [comment]
@tiyiprh I can increase the padding but the hover state is tricky. Because the click action directs users to a url it needs to be an anchor (`a href`) and not a button. Previously it was a button wrapped in an anchor, which is bad HTML with nested interactive elements.

The problem with the hover state is that if we change the background on hover it is possible that the text is obscured because it has an independent hover state. It's kind of hard to explain but I can show you if needed.

Although reading again, do you mean that the text remains white on hover but only the background changes from cyan to black? That's definitely something we can do because it doesn't risk colour contrast issues.

Thanks for the feedback.

**Comment by oraNod** [comment]
@tiyiprh Please take a look at https://ansible-community-website--258.org.readthedocs.build/en/258/

I think it's a good idea to increase the padding and this round of updates has lead to other improvements, so it's been really useful. I updated so all anchors on the homepage are more consistent and act more like buttons.

There's also a commit to make all buttons change to a black background on hover, including the platform button at the bottom. We can change it around but personally I prefer it when the text color changes on hover, not the background.

I found that "pool" on top of "cyan" passed the colour contrast tests and was using that throughout. It seemed to give a nice effect. The same with the platform text changing from white to black. Switching the background to black seems a little too jarring.

While we're at it, I'd like to make the hover action here more consistent with the "pip install ansible" button. Any thoughts you'd have there would be great too. Cheers.

**Comment by tiyiprh** [comment]
I think this looks good! I think the "pip install ansible" mirrors the same interaction so it works as well!

**Comment by tiyiprh** [comment]
Yes for consistency we should also make those black on hover. Can we actually change the "pip install ansible" to black on hover as well?

**Comment by oraNod** [comment]
@tiyiprh I've made those changes. I also updated the responsive design so the buttons all stack and go full width on mobile. I also made it so the community social icons go full width and have a bit of padding so they don't get too scrunched up on mobile, which is something I noticed.

Please take a look and let me know if you have any final nits. https://ansible-community-website--258.org.readthedocs.build/en/258/

**Comment by tiyiprh** [comment]
@oraNod Looks good!! I noticed the "pip install ansible" disappears on mobile, is that supposed to happen?

**Comment by oraNod** [comment]
@tiyiprh Thanks! Yes, we hide the "pip install ansible" on mobile because nobody is going to copy/paste that command into a terminal on their mobile device. Technically users could do that but I'm not so sure there's much of a use case there. Maybe just power users but they could skip to the install part of "Getting started" and figure it out.

As always I'm open to correction and improvement so let me know what you think there. Cheers.

**Comment by tiyiprh** [comment]
@oraNod I think that makes sense!
