### ISSUE TITLE
Build FAQ page

### ISSUE THREAD

**Issue by wbentley15** [ansible-community/community-website#286]
A new FAQ page needs to be crafted to host any community frequently asked questions and the content on this page should be included there: https://www.ansible.com/products/awx-project/faq

Project URL should be: www.ansible.com/faq

**Comment by Dule-martins** [comment]
The content on the page you share its URL talks about AWX Project, I thought the newly crafted page content should be about questions being ask about the community. 

I believe there is a different between community frequently ask questions and AWX project frequently ask questions.

So, why asking for the content to be included in the new FAQ page?

**Comment by oraNod** [comment]
@Dule-martins Thanks for the question. I believe the intention, partly, is to address many common questions that relate to the difference between community projects and corresponding downstream offerings that Red Hat brings to market. It is not often easy to distinguish between those two things, which can be somewhat problematic for a variety of reasons.

See the [Understanding Ansible, AWX, and Ansible Automation Platform](https://www.redhat.com/en/technologies/management/ansible/compare-awx-vs-ansible-automation-platform?hsLang=en-us) page as another example of the type of content that is meant to very clearly differentiate community projects from Red Hat products.

I would imagine the final FAQ page will not be limited to AWX content and will have other details related to the broader community. However AWX does have a large number of users and it is important to ensure that we continue to address those needs.

Does that answer your question? Also, I might ask if you have any of your own community FAQs that you feel would be good to include?

**Comment by wbentley15** [comment]
Totally cool with separate pages if the explanation does not satisfy the concern raised here.  Yes, Don was correct in stating the FAQ page will not be limited to just AWX content.

**Comment by Dule-martins** [comment]
Thank you @oraNod is fine, I get but what if we can have a separate page? Do you think is a much of an information for readers and do you also think community members might not visit the AWX page for information or AWX users might not also visit the community FAQ?

**Comment by Dule-martins** [comment]
Hey @oraNod and @wbentley15 I am asking this question to be sure about the directory where the new page will live, so kindly point that out for me.

I want to work on this issue.

**Comment by oraNod** [comment]
@Dule-martins There are a couple of ways this could go so I'll give you a shout when I've got a branch ready. If you have the time when that's ready you can work off that branch. Thanks.

**Comment by Dule-martins** [comment]
> @Dule-martins There are a couple of ways this could go so I'll give you a shout when I've got a branch ready. If you have the time when that's ready you can work off that branch. Thanks.

Will be waiting

**Comment by oraNod** [comment]
@Dule-martins Heads up that there is a PR open for this one but there has been some related discussion for whether or not a standalone FAQ page is needed. On the current `ansible.com` this is a sub-page with only AWX-specific content `https://www.ansible.com/products/awx-project/faq`. As you've already pointed out if that is the only content there isn't really a need for a standalone page.

@wbentley15 Do we know if there is any [other content](https://github.com/ansible-community/community-website/issues/286#issuecomment-1816854253) that really needs to go into the FAQ? I'm personally leaning towards the approach that we've used on the homepage, namely directing users to the forum.

**Comment by samccann** [comment]
I'm inclined to say the existing AWX faq belongs on an AWX page. Whether that's a part of the existing AWX page or an awx-faq page, either would work.

As for a community-based FAQ page - maybe we will need one, but I feel if we have a FAQ page it's because we didn't make  the rest of the pages clear enough. FAQs end up a dumping ground of information. They also are... pardon the pun.. FREQUENTLY ASKED questions... We don't have any yet, do we? 

I'd rather see us solve the AWX faq in an AWX way and leave the generic /faq/ page available for general community questions.

And ...just to be 'that person'... We could host FAQs in the forum instead :-)

**Comment by oraNod** [comment]
@samccann yes I prefer putting this stuff in the forum. granted the awx faq here is "legacy" for the website but I agree with the sentiment. in fact there's an faq for the import sanity test that I've wanted to recreate in the forum to see if we could move it out of docs: https://github.com/ansible/ansible-documentation/pull/294

**Comment by oraNod** [comment]
@wbentley15 After some discussion in slack and matrix it seems like the consensus is to include the FAQ as part of the AWX page. The FAQ will be available from `ansible.com/awx/#faq` to satisfy the needs of any teams that might require a direct link for content migrating to `redhat.com`.

If it transpires that we ultimately need a standalone FAQ page then it will be easy to move the content out of the AWX page. However creating an FAQ page now might result in us being stuck with a page that we don't really need / use and I want to be cautious about loading "legacy" content. Hope that makes sense. If you feel strongly otherwise and disagree, please feel free to reopen this issue and let me know. Thanks.
