### ISSUE TITLE
Add new link to top navigation

### ISSUE THREAD

**Issue by wbentley15** [ansible-community/community-website#297]
The RH Marketing team has asked if we can add a link pointing to the product at the top navigation of the website.  Open to discuss this further as a team, just wanted to leave a placeholder.

In my opinion I am open to the idea.  Would suggest adding it after the 'Documentation' label link and add the Red Hat Ansible Automation Platform logo that links to:  https://www.redhat.com/en/technologies/management/ansible.

**Comment by oraNod** [comment]
Unfortunately I feel this would result in a redundant link because the platform band already points to that url. [Here is an article](https://www.boia.org/blog/how-redundant-links-impact-accessibility) that explains the issue nicely.

To ensure absolute conformity with WCAG 2.1 guidelines, we removed a "Learn more about the platform" link from the Ansible band because it too was redundant with the platform band. While it is true that redundant links do not constitute a violation of accessibility I do not feel like it's the right thing for our users to include a redundant link.

With that in mind I would propose that we either put a link to that url in the top navigation and remove the platform band or leave the site as-is. I suppose the benefit of putting the link in the top nav means it will be available across all pages of the site.

Another thing we could do here would be to change the url in the platform band. However my understanding is that the marketing team want to point to that specific url only.

**Comment by oraNod** [comment]
@wbentley15 Now that we have the "Resources" sub-menu in the navigation I suppose we could add an entry for the platform - but this would require a new page. Although it could be a really brief set of content. Putting the link under "Resources" seems like a good spot though.
