### ISSUE TITLE
Migrate blog posts from current ansible.com to new site

### ISSUE THREAD

**Issue by grountre** [ansible-community/community-website#300]
A list of 119 blog posts currently on ansible.com/blog has been identified for migrating to the NEW ansible.com blog. 

I'm attaching a txt file with the list of blogs that should be migrated and I can provided an export of the entire current site upon request. My hope is that someone can create a script to programmatically migrate these posts and their content to the new site.
[adc-blog-migrations_1123.txt](https://github.com/ansible-community/community-website/files/13323165/adc-blog-migrations_1123.txt)

This issue is likely dependent on a blog layout being created on the new site and is a predecessor to the new site being launched. 

Let me know what questions exist.
-Graham (PM working with [wbentley15](https://github.com/wbentley15))

**Comment by oraNod** [comment]
@grountre I think we're good here and can close this issue. All the posts you've requested in that text file and in the google spreadsheet have been migrated to the new site.

You can find a list of all the urls of the migrated posts on our dev site in this file: 
[migrated-post-urls.txt](https://github.com/ansible-community/community-website/files/14052374/migrated-post-urls.txt)

You might observe that we've migrated 129 posts, which is more than requested. However, when checking the post migration I found one or two posts in a series that were not included in the list. It made sense to me to migrate all posts in the series. Additionally we migrated all the posts that were authored by the Ansible community team, which should account for the extras.

Finally we've configured the new site so that all the migrated posts will be available from the url context of "blog/" to maintain the current urls. This should ensure that all the requested urls remain the same on the new site once the domain switches to "ansible.com".

Please let me know if you have any questions about all this, any concerns, or if any additional work is needed in order to close this issue and consider the blog migration complete. Cheers.

**Comment by grountre** [comment]
@oraNod - This looks good. I checked your list against the lists we have on our end and I don't see any concerns with the additional posts you migrated. I think you can close this issue.
