### ISSUE TITLE
Subscribe section: Subscribe button doesn't seem to take you to a subscribe page.

### ISSUE THREAD

**Issue by tiyiprh** [ansible-community/community-website#351]
This is what appears when I click on "Subscribe" in the subscription section.

<img width="1722" alt="Screenshot 2024-01-03 at 2 30 00 PM" src="https://github.com/ansible-community/community-website/assets/98424339/5d3e2879-f503-4059-b275-ad3efca76e0e">

**Comment by oraNod** [comment]
Hmm. Yeah it's the RSS feed from the forum. That's the expected behaviour but maybe it's confusing / not very useful. Should we remove the subscribe button?

Or maybe we should point to this page: https://ansible.us19.list-manage.com/subscribe?u=56d874e027110e35dea0e03c1&id=d6635f5420

@cybette What do you think?

**Comment by cybette** [comment]
Yes let's use the mailchimp subscribe link, you can also use this shortened URL https://bit.ly/subscribe-bullhorn (points to the same page). Thanks!
